# Generated by Django 5.2.8 on 2026-05-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('cadastro_criado', 'Cadastro criado'), ('cadastro_atualizado', 'Cadastro atualizado'), ('inscricao_salva', 'Inscrição salva'), ('pontuacao_alterada', 'Pontuação alterada'), ('comprovante_upload', 'Upload de comprovante'), ('comprovante_download', 'Download de comprovante'), ('csv_exportado', 'CSV exportado'), ('dados_exportados_titular', 'Dados do titular exportados'), ('dados_excluidos_titular', 'Dados do titular excluídos')], max_length=40)),
                ('objeto_tipo', models.CharField(blank=True, max_length=120)),
                ('objeto_id', models.CharField(blank=True, max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
