# Generated by Django 5.2.8 on 2026-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('cadastro_criado', 'Cadastro criado'), ('cadastro_atualizado', 'Cadastro atualizado'), ('inscricao_salva', 'Inscrição salva'), ('pontuacao_alterada', 'Pontuação alterada'), ('comprovante_upload', 'Upload de comprovante'), ('comprovante_download', 'Download de comprovante'), ('csv_exportado', 'CSV exportado'), ('dados_exportados_titular', 'Dados do titular exportados'), ('dados_excluidos_titular', 'Dados do titular excluídos'), ('inscricao_revisada', 'Inscrição revisada')], max_length=40),
        ),
    ]
