# Generated by Django 5.2.8 on 2026-05-14 03:18

import apps.usuarios.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o CPF com 11 dígitos, sem pontos ou traços.', regex='^\\d{11}$')], verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=180, verbose_name='nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('vinculo', models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor'), ('colaborador_externo', 'Colaborador Externo')], max_length=30, verbose_name='vínculo')),
                ('instituicao', models.CharField(blank=True, max_length=180, verbose_name='instituição')),
                ('lattes', models.URLField(blank=True, verbose_name='currículo Lattes')),
                ('resumo', models.TextField(blank=True, verbose_name='resumo profissional')),
                ('perfil', models.CharField(choices=[('candidato', 'Candidato'), ('rh', 'RH'), ('coordenador', 'Coordenador'), ('admin', 'Administrador')], default='candidato', max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('rg', models.CharField(blank=True, max_length=30, verbose_name='RG')),
                ('orgao_emissor', models.CharField(blank=True, max_length=30, verbose_name='órgão emissor')),
                ('genero', models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao_informado', 'Prefiro não informar')], max_length=30, verbose_name='gênero')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=220, verbose_name='endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('nivel_formacao', models.CharField(blank=True, max_length=80, verbose_name='nível de formação')),
                ('area_atuacao', models.CharField(blank=True, max_length=120, verbose_name='área de atuação')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('aceite_lgpd', models.BooleanField(default=False, verbose_name='aceite LGPD')),
                ('aceite_lgpd_em', models.DateTimeField(blank=True, null=True, verbose_name='data/hora do aceite LGPD')),
                ('aceite_lgpd_versao', models.CharField(blank=True, max_length=30, verbose_name='versão do termo LGPD')),
                ('aceite_lgpd_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do aceite LGPD')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['nome_completo'],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
