# Generated by Django 5.2.8 on 2026-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='categoria_pretendida',
            field=models.CharField(blank=True, choices=[('pesquisador', 'Pesquisador(a)'), ('apoio_tecnico', 'Apoio técnico')], max_length=30, verbose_name='categoria pretendida'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciencia_credenciamento',
            field=models.BooleanField(default=False, verbose_name='ciência de que o credenciamento não garante vaga'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciencia_credenciamento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='consentimento_verificacao_bases',
            field=models.BooleanField(default=False, verbose_name='consentimento de verificação em bases internas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='consentimento_verificacao_bases_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='declaracao_veracidade',
            field=models.BooleanField(default=False, verbose_name='declaração de veracidade (art. 299 CP)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='declaracao_veracidade_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='disponibilidade_semanal',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='disponibilidade semanal (horas)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='maior_titulacao',
            field=models.CharField(blank=True, choices=[('tecnico', 'Médio/Técnico'), ('graduacao', 'Graduação'), ('especializacao', 'Especialização'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=30, verbose_name='maior titulação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nao_afastado_licenciado',
            field=models.BooleanField(blank=True, null=True, verbose_name='não afastado(a)/licenciado(a)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='servidor_ativo',
            field=models.BooleanField(blank=True, null=True, verbose_name='servidor(a) ativo(a)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('candidato', 'Candidato(a)'), ('rh', 'RH'), ('coordenador', 'Coordenador'), ('admin', 'Administrador')], default='candidato', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor(a)'), ('colaborador_externo', 'Colaborador(a) Externo(a)')], max_length=30, verbose_name='vínculo'),
        ),
    ]
