# Generated by Django 5.2.8 on 2026-05-14 03:18

import apps.inscricoes.models
import django.core.validators
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInscricao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor'), ('colaborador_externo', 'Colaborador Externo')], max_length=30, verbose_name='modalidade')),
                ('tipo_servidor', models.CharField(blank=True, choices=[('pesquisador', 'Pesquisador'), ('apoio_tecnico', 'Apoio técnico')], max_length=30, verbose_name='tipo de servidor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='pontuação total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('completa', 'Completa'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('indeferida', 'Indeferida')], default='pendente', max_length=30, verbose_name='status')),
                ('comprovantes_pdf', models.TextField(blank=True, max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF único de comprovantes')),
                ('comprovantes_pdf_nome_original', models.CharField(blank=True, max_length=255)),
                ('comprovantes_pdf_tamanho', models.PositiveIntegerField(default=0)),
                ('comprovantes_pdf_mime', models.CharField(blank=True, max_length=120)),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical inscrição',
                'verbose_name_plural': 'historical inscrições',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInscricaoItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pontuação solicitada')),
                ('pontuacao_validada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pontuação validada')),
                ('observacao_avaliacao', models.TextField(blank=True, verbose_name='observação da avaliação')),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical item da inscrição',
                'verbose_name_plural': 'historical itens da inscrição',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor'), ('colaborador_externo', 'Colaborador Externo')], max_length=30, verbose_name='modalidade')),
                ('tipo_servidor', models.CharField(blank=True, choices=[('pesquisador', 'Pesquisador'), ('apoio_tecnico', 'Apoio técnico')], max_length=30, verbose_name='tipo de servidor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='pontuação total')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('completa', 'Completa'), ('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('indeferida', 'Indeferida')], default='pendente', max_length=30, verbose_name='status')),
                ('comprovantes_pdf', models.FileField(blank=True, upload_to=apps.inscricoes.models.comprovante_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF único de comprovantes')),
                ('comprovantes_pdf_nome_original', models.CharField(blank=True, max_length=255)),
                ('comprovantes_pdf_tamanho', models.PositiveIntegerField(default=0)),
                ('comprovantes_pdf_mime', models.CharField(blank=True, max_length=120)),
                ('enviada_em', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pontuação solicitada')),
                ('pontuacao_validada', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='pontuação validada')),
                ('observacao_avaliacao', models.TextField(blank=True, verbose_name='observação da avaliação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'item da inscrição',
                'verbose_name_plural': 'itens da inscrição',
                'ordering': ['criterio__ordem'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('estudante', 'Estudante'), ('servidor', 'Servidor'), ('colaborador_externo', 'Colaborador Externo')], max_length=30, verbose_name='modalidade')),
                ('tipo_servidor', models.CharField(blank=True, choices=[('pesquisador', 'Pesquisador'), ('apoio_tecnico', 'Apoio técnico')], max_length=30, verbose_name='tipo de servidor')),
                ('item_id', models.CharField(max_length=80, verbose_name='identificador do item')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('criterio', models.CharField(max_length=500, verbose_name='critério')),
                ('regra', models.CharField(max_length=500, verbose_name='regra de pontuação')),
                ('maximo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='pontuação máxima')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'critério do edital',
                'verbose_name_plural': 'critérios do edital',
                'ordering': ['modalidade', 'tipo_servidor', 'ordem'],
                'constraints': [models.UniqueConstraint(fields=('modalidade', 'tipo_servidor', 'item_id'), name='uniq_criterio_por_modalidade_tipo_item')],
            },
        ),
    ]
