# Generated by Django 5.2.8 on 2026-05-14 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinscricao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinscricao',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinscricaoitem',
            name='criterio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inscricoes.criterioedital'),
        ),
        migrations.AddField(
            model_name='historicalinscricaoitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inscricao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinscricaoitem',
            name='inscricao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inscricoes.inscricao'),
        ),
        migrations.AddField(
            model_name='inscricaoitem',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inscricao', to='inscricoes.criterioedital'),
        ),
        migrations.AddField(
            model_name='inscricaoitem',
            name='inscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inscricoes.inscricao'),
        ),
        migrations.AddConstraint(
            model_name='inscricaoitem',
            constraint=models.UniqueConstraint(fields=('inscricao', 'criterio'), name='uniq_item_por_inscricao_criterio'),
        ),
    ]
