# Generated by Django 5.2.8 on 2026-05-21 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinscricao',
            name='parecer_geral',
            field=models.TextField(blank=True, verbose_name='parecer geral'),
        ),
        migrations.AddField(
            model_name='historicalinscricao',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisado em'),
        ),
        migrations.AddField(
            model_name='historicalinscricao',
            name='revisado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='revisado por'),
        ),
        migrations.AddField(
            model_name='historicalinscricao',
            name='total_validado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='pontuação total validada'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='parecer_geral',
            field=models.TextField(blank=True, verbose_name='parecer geral'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='revisado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='revisado em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='revisado por'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='total_validado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='pontuação total validada'),
        ),
    ]
